"""
A.E.G.I.S. Memory Manager.

Provides the public API for:

- Explicit memory storage
- Automatic memory candidate storage
- Memory retrieval
- Recent memory listing
- Memory inspection
- Memory deletion
- Complete memory clearing
- Duplicate detection
- Conflict detection
- Conflict resolution
- Memory consolidation
- Memory lifecycle management
- Memory updating
- Memory supersession
- Memory restoration
- Memory archiving
- Semantic embedding persistence

The MemoryManager is the mutation boundary for persistent memory.

The LLM and higher-level A.E.G.I.S. components should never
write directly to SQLite.
"""

from __future__ import annotations

import re

from .conflicts import (
    ConflictResult,
    MemoryConflictDetector,
    MemoryRelationship,
)
from .consolidation import MemoryConsolidator
from .embeddings import MemoryEmbedder
from .models import (
    Memory,
    MemoryStatus,
    MemoryType,
)
from .policy import MemoryPolicy
from .resolution import (
    MemoryConflictResolver,
    ResolutionAction,
    ResolutionDecision,
)
from .retrieval import MemoryRetriever
from .store import SQLiteMemoryStore


class MemoryManager:
    """
    Public API for A.E.G.I.S. persistent memory.

    MemoryManager coordinates:

        Policy
            ↓
        Memory construction
            ↓
        Consolidation
            ↓
        Conflict resolution
            ↓
        SQLite persistence
            ↓
        Semantic embedding persistence

    All memory mutations pass through this class.

    Embeddings are generated by MemoryEmbedder and persisted
    through SQLiteMemoryStore.
    """

    def __init__(
        self,
        database_path: str = "data/aegis_memory.db",
        policy: MemoryPolicy | None = None,
    ):
        self.store = SQLiteMemoryStore(
            database_path
        )

        self.policy = (
            policy
            if policy is not None
            else MemoryPolicy()
        )

        self.retriever = MemoryRetriever(
            self.store
        )

        self.embedder = MemoryEmbedder()

        self.conflict_detector = (
            MemoryConflictDetector()
        )

        self.conflict_resolver = (
            MemoryConflictResolver()
        )

        self.consolidator = MemoryConsolidator(
            detector=self.conflict_detector,
            resolver=self.conflict_resolver,
        )

    # =========================================================
    # BASIC MEMORY STORAGE
    # =========================================================

    def remember(
        self,
        content: str,
        memory_type: MemoryType = MemoryType.EPISODIC,
        *,
        importance: float = 0.5,
        confidence: float = 1.0,
        sensitivity: float = 0.0,
        source: str = "conversation",
        tags: list[str] | None = None,
        metadata: dict | None = None,
        explicit: bool = False,
    ) -> Memory | None:
        """
        Store a memory after passing it through MemoryPolicy.

        When successfully stored, a semantic embedding is
        generated and persisted alongside the memory.

        Returns:
            Memory when stored.
            None when rejected or empty.
        """

        content = content.strip()

        if not content:
            return None

        memory = Memory(
            content=content,
            memory_type=memory_type,
            importance=self._clamp(
                importance
            ),
            confidence=self._clamp(
                confidence
            ),
            sensitivity=self._clamp(
                sensitivity
            ),
            source=source,
            tags=tags or [],
            metadata=metadata or {},
        )

        if not self.policy.should_store(
            memory,
            explicit=explicit,
        ):
            return None

        stored = self.store.save(
            memory
        )

        # -----------------------------------------------------
        # Semantic embedding
        # -----------------------------------------------------

        self._save_embedding(
            memory
        )

        return stored

    # =========================================================
    # MEMORY RETRIEVAL
    # =========================================================

    def recall(
        self,
        query: str,
        limit: int = 8,
    ) -> list[Memory]:
        """
        Retrieve memories relevant to a query.

        The current retriever remains responsible for retrieval
        strategy. Semantic retrieval will be integrated there
        in the next retrieval stage.
        """

        query = query.strip()

        if not query:
            return []

        return self.retriever.retrieve(
            query,
            limit=limit,
        )

    def recent(
        self,
        memory_type: MemoryType | None = None,
        status: MemoryStatus | None = None,
        limit: int = 20,
    ) -> list[Memory]:
        """
        Return recent memories with optional filters.
        """

        return self.store.list(
            memory_type=memory_type,
            status=status,
            limit=limit,
        )

    def get(
        self,
        memory_id: str,
    ) -> Memory | None:
        """
        Retrieve a single memory by ID.
        """

        memory_id = memory_id.strip()

        if not memory_id:
            return None

        return self.store.get(
            memory_id
        )

    # =========================================================
    # MEMORY DELETION
    # =========================================================

    def forget(
        self,
        memory_id: str,
    ) -> bool:
        """
        Delete one memory by ID.

        The SQLite store removes the associated embedding
        through the embedding table's foreign-key cascade.
        """

        memory_id = memory_id.strip()

        if not memory_id:
            return False

        return self.store.delete(
            memory_id
        )

    def clear(self) -> int:
        """
        Delete every stored memory.

        Associated embeddings are removed by the SQLite store.
        """

        return self.store.clear()

    # =========================================================
    # MEMORY INSPECTION
    # =========================================================

    def format_memory(
        self,
        memory: Memory,
    ) -> str:
        """
        Convert one memory into a human-readable inspection view.
        """

        tags = (
            ", ".join(memory.tags)
            if memory.tags
            else "None"
        )

        return (
            f"Memory ID: {memory.id}\n"
            f"Type: {memory.memory_type.value}\n"
            f"Status: {memory.status.value}\n"
            f"Content: {memory.content}\n"
            f"Importance: {memory.importance:.2f}\n"
            f"Confidence: {memory.confidence:.2f}\n"
            f"Sensitivity: {memory.sensitivity:.2f}\n"
            f"Source: {memory.source}\n"
            f"Tags: {tags}\n"
            f"Created: {memory.created_at}\n"
            f"Updated: {memory.updated_at}\n"
            f"Stale: {memory.stale_at}\n"
            f"Archived: {memory.archived_at}\n"
            f"Superseded By: {memory.superseded_by}"
        )

    def format_context(
        self,
        query: str,
        limit: int = 8,
    ) -> str:
        """
        Format relevant memories for LLM context injection.
        """

        memories = self.recall(
            query,
            limit=limit,
        )

        if not memories:
            return (
                "No relevant memories were found."
            )

        lines = [
            "Relevant A.E.G.I.S. memories:"
        ]

        for memory in memories:
            lines.append(
                f"- [{memory.memory_type.value}] "
                f"{memory.content}"
            )

        return "\n".join(
            lines
        )

    # =========================================================
    # DUPLICATE / SIMILARITY DETECTION
    # =========================================================

    @staticmethod
    def _normalize_text(
        text: str,
    ) -> set[str]:
        """
        Convert text into normalized lexical tokens.
        """

        return {
            token
            for token in re.findall(
                r"\b[a-zA-Z0-9_]+\b",
                text.lower(),
            )
            if len(token) > 2
        }

    @classmethod
    def _similarity(
        cls,
        first: str,
        second: str,
    ) -> float:
        """
        Calculate Jaccard token similarity.
        """

        first_tokens = cls._normalize_text(
            first
        )

        second_tokens = cls._normalize_text(
            second
        )

        if (
            not first_tokens
            or not second_tokens
        ):
            return 0.0

        intersection = (
            first_tokens
            & second_tokens
        )

        union = (
            first_tokens
            | second_tokens
        )

        return (
            len(intersection)
            / len(union)
        )

    def find_similar(
        self,
        content: str,
        threshold: float = 0.60,
        limit: int = 10,
    ) -> list[tuple[Memory, float]]:
        """
        Find active memories similar to a candidate.
        """

        content = content.strip()

        if not content:
            return []

        memories = self.recent(
            status=MemoryStatus.ACTIVE,
            limit=1000,
        )

        matches: list[
            tuple[Memory, float]
        ] = []

        for memory in memories:
            similarity = self._similarity(
                content,
                memory.content,
            )

            if similarity >= threshold:
                matches.append(
                    (
                        memory,
                        similarity,
                    )
                )

        matches.sort(
            key=lambda item: item[1],
            reverse=True,
        )

        return matches[:limit]

    # =========================================================
    # CONFLICT DETECTION
    # =========================================================

    def detect_conflict(
        self,
        content: str,
        *,
        memory_type: MemoryType = MemoryType.EPISODIC,
        importance: float = 0.5,
        confidence: float = 1.0,
        sensitivity: float = 0.0,
        source: str = "conflict_detection",
        tags: list[str] | None = None,
    ) -> list[
        tuple[
            Memory,
            ConflictResult,
        ]
    ]:
        """
        Compare a candidate against active memories.

        Only DUPLICATE and CONFLICT relationships are returned.

        This method does not modify memory.
        """

        content = content.strip()

        if not content:
            return []

        candidate = Memory(
            content=content,
            memory_type=memory_type,
            importance=self._clamp(
                importance
            ),
            confidence=self._clamp(
                confidence
            ),
            sensitivity=self._clamp(
                sensitivity
            ),
            source=source,
            tags=tags or [],
        )

        active_memories = self.recent(
            status=MemoryStatus.ACTIVE,
            limit=1000,
        )

        results: list[
            tuple[
                Memory,
                ConflictResult,
            ]
        ] = []

        for existing in active_memories:
            result = (
                self.conflict_detector.compare(
                    existing,
                    candidate,
                )
            )

            if result.relationship in {
                MemoryRelationship.DUPLICATE,
                MemoryRelationship.CONFLICT,
            }:
                results.append(
                    (
                        existing,
                        result,
                    )
                )

        results.sort(
            key=lambda item: item[1].score,
            reverse=True,
        )

        return results

    # =========================================================
    # CONFLICT / RESOLUTION
    # =========================================================

    def apply_resolution(
        self,
        decision: ResolutionDecision,
        *,
        approve_destructive: bool = False,
        memory_type: MemoryType = MemoryType.EPISODIC,
        importance: float = 0.5,
        confidence: float = 1.0,
        sensitivity: float = 0.0,
        source: str = "memory_resolution",
        tags: list[str] | None = None,
        metadata: dict | None = None,
    ) -> tuple[
        Memory | None,
        Memory | None,
    ]:
        """
        Apply an already-created resolution decision.

        Returns:

            (existing_memory, resulting_memory)

        SUPERSEDE_EXISTING requires explicit approval.
        """

        # -----------------------------------------------------
        # REJECT
        # -----------------------------------------------------

        if (
            decision.action
            == ResolutionAction.REJECT_CANDIDATE
        ):
            existing = None

            if decision.existing_memory_id:
                existing = self.get(
                    decision.existing_memory_id
                )

            return (
                existing,
                None,
            )

        # -----------------------------------------------------
        # KEEP EXISTING
        # -----------------------------------------------------

        if (
            decision.action
            == ResolutionAction.KEEP_EXISTING
        ):
            existing = None

            if decision.existing_memory_id:
                existing = self.get(
                    decision.existing_memory_id
                )

            return (
                existing,
                existing,
            )

        # -----------------------------------------------------
        # KEEP BOTH
        # -----------------------------------------------------

        if (
            decision.action
            == ResolutionAction.KEEP_BOTH
        ):
            stored = self.remember(
                decision.candidate_content,
                memory_type=memory_type,
                importance=importance,
                confidence=confidence,
                sensitivity=sensitivity,
                source=source,
                tags=tags,
                metadata=metadata,
                explicit=False,
            )

            return (
                None,
                stored,
            )

        # -----------------------------------------------------
        # SUPERSEDE
        # -----------------------------------------------------

        if (
            decision.action
            == ResolutionAction.SUPERSEDE_EXISTING
        ):
            existing = None

            if decision.existing_memory_id:
                existing = self.get(
                    decision.existing_memory_id
                )

            if not approve_destructive:
                return (
                    existing,
                    None,
                )

            if not decision.existing_memory_id:
                return (
                    None,
                    None,
                )

            old_memory, new_memory = (
                self.supersede_memory(
                    decision.existing_memory_id,
                    decision.candidate_content,
                    memory_type=memory_type,
                    importance=importance,
                    confidence=confidence,
                    sensitivity=sensitivity,
                    source=source,
                    tags=tags,
                    metadata=metadata,
                )
            )

            return (
                old_memory,
                new_memory,
            )

        return (
            None,
            None,
        )

    def resolve_candidate(
        self,
        content: str,
        memory_type: MemoryType = MemoryType.EPISODIC,
        *,
        importance: float = 0.5,
        confidence: float = 1.0,
        sensitivity: float = 0.0,
        source: str = "automatic_extraction",
        tags: list[str] | None = None,
        metadata: dict | None = None,
    ) -> tuple[
        ResolutionDecision,
        Memory | None,
    ]:
        """
        Resolve and optionally store an automatically generated
        memory candidate.

        Pipeline:

            Candidate
                ↓
            Governance
                ↓
            Consolidation
                ↓
            Resolution
                ↓
            Application
        """

        content = content.strip()

        # -----------------------------------------------------
        # Empty candidate
        # -----------------------------------------------------

        if not content:
            return (
                ResolutionDecision(
                    action=ResolutionAction.REJECT_CANDIDATE,
                    existing_memory_id=None,
                    candidate_content="",
                    relationship=MemoryRelationship.UNRELATED,
                    confidence=0.0,
                    reason=(
                        "The candidate memory is empty."
                    ),
                    requires_confirmation=False,
                ),
                None,
            )

        importance = self._clamp(
            importance
        )

        confidence = self._clamp(
            confidence
        )

        sensitivity = self._clamp(
            sensitivity
        )

        # -----------------------------------------------------
        # Sensitive candidate
        # -----------------------------------------------------

        if sensitivity > 0:
            return (
                ResolutionDecision(
                    action=ResolutionAction.REJECT_CANDIDATE,
                    existing_memory_id=None,
                    candidate_content=content,
                    relationship=MemoryRelationship.UNRELATED,
                    confidence=confidence,
                    reason=(
                        "The candidate contains sensitive "
                        "information and was rejected by the "
                        "automatic memory policy."
                    ),
                    requires_confirmation=True,
                ),
                None,
            )

        # -----------------------------------------------------
        # Build candidate
        # -----------------------------------------------------

        candidate = Memory(
            content=content,
            memory_type=memory_type,
            importance=importance,
            confidence=confidence,
            sensitivity=sensitivity,
            source=source,
            tags=tags or [],
            metadata=metadata or {},
        )

        # -----------------------------------------------------
        # Retrieve active memories
        # -----------------------------------------------------

        active_memories = self.recent(
            status=MemoryStatus.ACTIVE,
            limit=1000,
        )

        # -----------------------------------------------------
        # Consolidate
        # -----------------------------------------------------

        proposal = self.consolidator.consolidate(
            candidate,
            active_memories,
            allow_supersession=False,
        )

        decision = proposal.decision

        # -----------------------------------------------------
        # Apply decision
        # -----------------------------------------------------

        existing, resulting = (
            self.apply_resolution(
                decision,
                approve_destructive=False,
                memory_type=memory_type,
                importance=importance,
                confidence=confidence,
                sensitivity=sensitivity,
                source=source,
                tags=tags,
                metadata=metadata,
            )
        )

        # -----------------------------------------------------
        # REJECT
        # -----------------------------------------------------

        if (
            decision.action
            == ResolutionAction.REJECT_CANDIDATE
        ):
            return (
                decision,
                existing,
            )

        # -----------------------------------------------------
        # KEEP EXISTING
        # -----------------------------------------------------

        if (
            decision.action
            == ResolutionAction.KEEP_EXISTING
        ):
            return (
                decision,
                existing,
            )

        # -----------------------------------------------------
        # KEEP BOTH
        # -----------------------------------------------------

        if (
            decision.action
            == ResolutionAction.KEEP_BOTH
        ):
            if resulting is None:
                rejected = ResolutionDecision(
                    action=ResolutionAction.REJECT_CANDIDATE,
                    existing_memory_id=(
                        proposal.existing_memory.id
                        if proposal.existing_memory
                        is not None
                        else None
                    ),
                    candidate_content=content,
                    relationship=decision.relationship,
                    confidence=decision.confidence,
                    reason=(
                        "The consolidator allowed the "
                        "candidate, but MemoryPolicy rejected "
                        "it during storage."
                    ),
                    requires_confirmation=False,
                )

                return (
                    rejected,
                    None,
                )

            return (
                decision,
                resulting,
            )

        # -----------------------------------------------------
        # SUPERSEDE
        # -----------------------------------------------------

        return (
            decision,
            existing,
        )

    # =========================================================
    # LEGACY AUTOMATIC CANDIDATE API
    # =========================================================

    def store_candidate(
        self,
        content: str,
        memory_type: MemoryType,
        *,
        importance: float,
        confidence: float,
        sensitivity: float,
        source: str = "automatic_extraction",
        tags: list[str] | None = None,
    ) -> tuple[
        str,
        Memory | None,
    ]:
        """
        Process an automatically extracted memory candidate.

        Returns:

            ("stored", Memory)
            ("duplicate", existing_memory)
            ("conflict", existing_memory)
            ("rejected", None)

        This method is retained for backward compatibility.
        New integrations should prefer resolve_candidate().
        """

        decision, memory = (
            self.resolve_candidate(
                content,
                memory_type=memory_type,
                importance=importance,
                confidence=confidence,
                sensitivity=sensitivity,
                source=source,
                tags=tags,
            )
        )

        if (
            decision.action
            == ResolutionAction.REJECT_CANDIDATE
        ):
            if (
                decision.relationship
                == MemoryRelationship.DUPLICATE
            ):
                return (
                    "duplicate",
                    memory,
                )

            if (
                decision.relationship
                == MemoryRelationship.CONFLICT
            ):
                return (
                    "conflict",
                    memory,
                )

            return (
                "rejected",
                None,
            )

        if (
            decision.action
            == ResolutionAction.KEEP_EXISTING
        ):
            return (
                "conflict",
                memory,
            )

        if memory is not None:
            return (
                "stored",
                memory,
            )

        return (
            "rejected",
            None,
        )

    # =========================================================
    # MEMORY LIFECYCLE / UPDATES
    # =========================================================

    def update_memory(
        self,
        memory_id: str,
        content: str,
        *,
        importance: float | None = None,
        confidence: float | None = None,
        sensitivity: float | None = None,
        tags: list[str] | None = None,
        metadata: dict | None = None,
    ) -> Memory | None:
        """
        Update an existing memory in place.

        The semantic embedding is regenerated after the
        memory content is updated.
        """

        memory_id = memory_id.strip()
        content = content.strip()

        if not memory_id or not content:
            return None

        memory = self.get(
            memory_id
        )

        if memory is None:
            return None

        if memory.status in {
            MemoryStatus.ARCHIVED,
            MemoryStatus.SUPERSEDED,
        }:
            return None

        memory.content = content

        if importance is not None:
            memory.importance = self._clamp(
                importance
            )

        if confidence is not None:
            memory.confidence = self._clamp(
                confidence
            )

        if sensitivity is not None:
            memory.sensitivity = self._clamp(
                sensitivity
            )

        if tags is not None:
            memory.tags = list(
                tags
            )

        if metadata is not None:
            memory.metadata = dict(
                metadata
            )

        memory.activate()

        stored = self.store.save(
            memory
        )

        self._save_embedding(
            memory
        )

        return stored

    def supersede_memory(
        self,
        old_memory_id: str,
        new_content: str,
        *,
        memory_type: MemoryType | None = None,
        importance: float = 0.5,
        confidence: float = 1.0,
        sensitivity: float = 0.0,
        source: str = "memory_update",
        tags: list[str] | None = None,
        metadata: dict | None = None,
    ) -> tuple[
        Memory | None,
        Memory | None,
    ]:
        """
        Replace an existing memory while preserving history.

        The replacement memory is created through remember(),
        which also creates its semantic embedding.

        The old memory is then marked SUPERSEDED.
        """

        old_memory_id = (
            old_memory_id.strip()
        )

        new_content = (
            new_content.strip()
        )

        if (
            not old_memory_id
            or not new_content
        ):
            return (
                None,
                None,
            )

        old_memory = self.get(
            old_memory_id
        )

        if old_memory is None:
            return (
                None,
                None,
            )

        if (
            old_memory.status
            != MemoryStatus.ACTIVE
        ):
            return (
                None,
                None,
            )

        importance = self._clamp(
            importance
        )

        confidence = self._clamp(
            confidence
        )

        sensitivity = self._clamp(
            sensitivity
        )

        replacement_metadata = dict(
            metadata or {}
        )

        replacement_metadata[
            "supersedes_memory_id"
        ] = old_memory.id

        if memory_type is None:
            memory_type = (
                old_memory.memory_type
            )

        new_memory = self.remember(
            new_content,
            memory_type=memory_type,
            importance=importance,
            confidence=confidence,
            sensitivity=sensitivity,
            source=source,
            tags=tags,
            metadata=replacement_metadata,
            explicit=False,
        )

        if new_memory is None:
            return (
                None,
                None,
            )

        old_memory.supersede(
            new_memory.id
        )

        self.store.save(
            old_memory
        )

        return (
            old_memory,
            new_memory,
        )

    def restore_memory(
        self,
        memory_id: str,
    ) -> Memory | None:
        """
        Reactivate a stale memory.

        Its existing embedding remains valid because the memory
        content has not changed.
        """

        memory_id = memory_id.strip()

        if not memory_id:
            return None

        memory = self.get(
            memory_id
        )

        if memory is None:
            return None

        if (
            memory.status
            != MemoryStatus.STALE
        ):
            return None

        memory.activate()

        return self.store.save(
            memory
        )

    def archive_memory(
        self,
        memory_id: str,
    ) -> Memory | None:
        """
        Archive a memory while retaining it in storage.

        Its embedding remains stored for historical access, but
        normal retrieval excludes the archived memory.
        """

        memory_id = memory_id.strip()

        if not memory_id:
            return None

        memory = self.get(
            memory_id
        )

        if memory is None:
            return None

        if memory.status in {
            MemoryStatus.ARCHIVED,
            MemoryStatus.SUPERSEDED,
        }:
            return None

        memory.archive()

        return self.store.save(
            memory
        )

    def stale_memory(
        self,
        memory_id: str,
    ) -> Memory | None:
        """
        Mark an active memory as stale.

        Its embedding remains valid because the memory content
        has not changed.
        """

        memory_id = memory_id.strip()

        if not memory_id:
            return None

        memory = self.get(
            memory_id
        )

        if memory is None:
            return None

        if (
            memory.status
            != MemoryStatus.ACTIVE
        ):
            return None

        memory.mark_stale()

        return self.store.save(
            memory
        )

    # =========================================================
    # EMBEDDING HELPERS
    # =========================================================

    def _save_embedding(
        self,
        memory: Memory,
    ) -> None:
        """
        Generate and persist the semantic embedding for a memory.

        Centralizing this operation ensures remember() and
        update_memory() use exactly the same embedding pipeline.
        """

        embedding = self.embedder.encode(
            memory.content
        )

        self.store.save_embedding(
            memory.id,
            embedding,
            self.embedder.model_name,
        )

    # =========================================================
    # UTILITIES
    # =========================================================

    @staticmethod
    def _clamp(
        value: float,
    ) -> float:
        """
        Clamp a numerical score to [0.0, 1.0].
        """

        try:
            value = float(
                value
            )
        except (
            TypeError,
            ValueError,
        ):
            return 0.0

        return max(
            0.0,
            min(
                1.0,
                value,
            )
        )