"""
A.E.G.I.S. Memory Retrieval.

Hybrid retrieval combines:

    1. Lexical candidate discovery through SQLite.
    2. Semantic candidate discovery through persisted embeddings.
    3. Multi-signal ranking through MemoryScorer.

The retrieval layer does not modify memories.

Semantic embeddings are generated by MemoryEmbedder and loaded
from SQLiteMemoryStore.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from .embeddings import MemoryEmbedder
from .models import Memory, MemoryStatus
from .scoring import MemoryScorer
from .store import SQLiteMemoryStore


@dataclass(frozen=True)
class RetrievalCandidate:
    """
    Internal retrieval candidate.

    A candidate may have:

        - lexical score
        - semantic score
        - both

    The object is immutable so retrieval cannot accidentally
    mutate persistent memory state.
    """

    memory: Memory

    lexical_score: float = 0.0

    semantic_score: float = 0.0


class MemoryRetriever:
    """
    Hybrid memory retriever.

    Retrieval happens in three stages:

        Stage 1:
            Lexical candidate discovery.

        Stage 2:
            Semantic candidate discovery.

        Stage 3:
            Candidate fusion followed by MemoryScorer ranking.

    Existing lexical retrieval remains available even when an
    embedding is missing.
    """

    DEFAULT_SEMANTIC_THRESHOLD = 0.20

    DEFAULT_LEXICAL_WEIGHT = 0.45

    DEFAULT_SEMANTIC_WEIGHT = 0.55

    def __init__(
        self,
        store: SQLiteMemoryStore,
        scorer: MemoryScorer | None = None,
        embedder: MemoryEmbedder | None = None,
        *,
        semantic_threshold: float = DEFAULT_SEMANTIC_THRESHOLD,
        lexical_weight: float = DEFAULT_LEXICAL_WEIGHT,
        semantic_weight: float = DEFAULT_SEMANTIC_WEIGHT,
    ):
        self.store = store

        self.scorer = (
            scorer
            if scorer is not None
            else MemoryScorer()
        )

        self.embedder = (
            embedder
            if embedder is not None
            else MemoryEmbedder()
        )

        self.semantic_threshold = max(
            0.0,
            min(
                1.0,
                float(
                    semantic_threshold
                ),
            ),
        )

        self.lexical_weight = max(
            0.0,
            float(
                lexical_weight
            ),
        )

        self.semantic_weight = max(
            0.0,
            float(
                semantic_weight
            ),
        )

        self._normalize_weights()

    # =========================================================
    # PUBLIC RETRIEVAL
    # =========================================================

    def retrieve(
        self,
        query: str,
        limit: int = 8,
    ) -> list[Memory]:
        """
        Retrieve memories using hybrid lexical + semantic search.

        The public API remains:

            retrieve(query, limit)

        Only ACTIVE memories participate in normal retrieval.
        """

        query = query.strip()

        if not query:
            return []

        limit = max(
            1,
            int(limit),
        )

        candidate_limit = max(
            limit * 4,
            20,
        )

        candidates = self._collect_candidates(
            query,
            candidate_limit,
        )

        if not candidates:
            return []

        ranked = self._rank_candidates(
            candidates,
            query,
        )

        return [
            candidate.memory
            for candidate in ranked[:limit]
        ]

    # =========================================================
    # LEXICAL RETRIEVAL
    # =========================================================

    def lexical_candidates(
        self,
        query: str,
        limit: int = 20,
    ) -> list[Memory]:
        """
        Return lexical candidates only.

        This preserves the original retrieval behavior and is
        useful for debugging and fallback behavior.
        """

        query = query.strip()

        if not query:
            return []

        return self.store.search_text(
            query,
            limit=max(
                1,
                int(limit),
            ),
        )

    # =========================================================
    # SEMANTIC RETRIEVAL
    # =========================================================

    def semantic_candidates(
        self,
        query: str,
        limit: int = 20,
    ) -> list[
        tuple[
            Memory,
            float,
        ]
    ]:
        """
        Return semantic candidates as:

            (memory, similarity)

        Only ACTIVE memories with a compatible persisted
        embedding are considered.
        """

        query = query.strip()

        if not query:
            return []

        limit = max(
            1,
            int(limit),
        )

        query_embedding = (
            self.embedder.encode(
                query
            )
        )

        memories = self.store.list(
            status=MemoryStatus.ACTIVE,
            limit=1000,
        )

        results: list[
            tuple[
                Memory,
                float,
            ]
        ] = []

        for memory in memories:
            stored = (
                self.store.get_embedding(
                    memory.id
                )
            )

            if stored is None:
                continue

            (
                embedding,
                model_name,
                dimensions,
                _created_at,
            ) = stored

            # -------------------------------------------------
            # Do not compare embeddings produced by different
            # models.
            # -------------------------------------------------

            if (
                model_name
                != self.embedder.model_name
            ):
                continue

            if (
                dimensions
                != query_embedding.size
            ):
                continue

            try:
                similarity = (
                    self.embedder.vector_similarity(
                        query_embedding,
                        embedding,
                    )
                )

            except ValueError:
                continue

            if (
                similarity
                >= self.semantic_threshold
            ):
                results.append(
                    (
                        memory,
                        similarity,
                    )
                )

        results.sort(
            key=lambda item: (
                item[1],
                item[0].importance,
                item[0].confidence,
                item[0].updated_at,
            ),
            reverse=True,
        )

        return results[:limit]

    # =========================================================
    # CANDIDATE COLLECTION
    # =========================================================

    def _collect_candidates(
        self,
        query: str,
        limit: int,
    ) -> list[RetrievalCandidate]:
        """
        Collect and merge lexical and semantic candidates.
        """

        lexical = self.lexical_candidates(
            query,
            limit=limit,
        )

        semantic = self.semantic_candidates(
            query,
            limit=limit,
        )

        candidates: dict[
            str,
            RetrievalCandidate,
        ] = {}

        # -----------------------------------------------------
        # Lexical candidates
        # -----------------------------------------------------

        lexical_scores = self._lexical_scores(
            lexical,
            query,
        )

        for memory in lexical:
            candidates[
                memory.id
            ] = RetrievalCandidate(
                memory=memory,
                lexical_score=lexical_scores.get(
                    memory.id,
                    0.0,
                ),
                semantic_score=0.0,
            )

        # -----------------------------------------------------
        # Semantic candidates
        # -----------------------------------------------------

        for (
            memory,
            semantic_score,
        ) in semantic:

            existing = candidates.get(
                memory.id
            )

            if existing is None:
                candidates[
                    memory.id
                ] = RetrievalCandidate(
                    memory=memory,
                    lexical_score=0.0,
                    semantic_score=semantic_score,
                )

            else:
                candidates[
                    memory.id
                ] = RetrievalCandidate(
                    memory=existing.memory,
                    lexical_score=existing.lexical_score,
                    semantic_score=semantic_score,
                )

        return list(
            candidates.values()
        )

    # =========================================================
    # RANKING
    # =========================================================

    def _rank_candidates(
        self,
        candidates: list[RetrievalCandidate],
        query: str,
    ) -> list[RetrievalCandidate]:
        """
        Rank hybrid candidates.

        Hybrid relevance is combined with the existing
        MemoryScorer ranking system.
        """

        scored: list[
            tuple[
                RetrievalCandidate,
                float,
            ]
        ] = []

        for candidate in candidates:

            memory_score = (
                self.scorer.score(
                    candidate.memory,
                    query,
                )
            )

            hybrid_relevance = (
                candidate.lexical_score
                * self.lexical_weight
                + candidate.semantic_score
                * self.semantic_weight
            )

            final_score = (
                0.60
                * hybrid_relevance
                + 0.40
                * memory_score
            )

            final_score = max(
                0.0,
                min(
                    1.0,
                    final_score,
                ),
            )

            scored.append(
                (
                    candidate,
                    final_score,
                )
            )

        scored.sort(
            key=lambda item: (
                item[1],
                item[0].memory.importance,
                item[0].memory.confidence,
                item[0].memory.updated_at,
            ),
            reverse=True,
        )

        return [
            candidate
            for candidate, _score
            in scored
        ]

    # =========================================================
    # LEXICAL SCORE
    # =========================================================

    def _lexical_scores(
        self,
        memories: list[Memory],
        query: str,
    ) -> dict[str, float]:
        """
        Calculate normalized lexical relevance for each
        lexical candidate.

        MemoryScorer remains the authoritative general-purpose
        scoring component. This score exists specifically for
        hybrid candidate fusion.
        """

        scores: dict[
            str,
            float,
        ] = {}

        for memory in memories:
            scores[
                memory.id
            ] = self._lexical_relevance(
                memory,
                query,
            )

        return scores

    def _lexical_relevance(
        self,
        memory: Memory,
        query: str,
    ) -> float:
        """
        Calculate lexical relevance using the existing scorer.
        """

        return max(
            0.0,
            min(
                1.0,
                self.scorer.relevance(
                    memory,
                    query,
                ),
            ),
        )

    # =========================================================
    # WEIGHT NORMALIZATION
    # =========================================================

    def _normalize_weights(
        self,
    ) -> None:
        """
        Normalize lexical and semantic weights to sum to 1.
        """

        total = (
            self.lexical_weight
            + self.semantic_weight
        )

        if total <= 0.0:
            self.lexical_weight = (
                self.DEFAULT_LEXICAL_WEIGHT
            )

            self.semantic_weight = (
                self.DEFAULT_SEMANTIC_WEIGHT
            )

            total = (
                self.lexical_weight
                + self.semantic_weight
            )

        self.lexical_weight /= total
        self.semantic_weight /= total